#!/usr/bin/env bash
# Install strip-coauthor as a git pre-push hook.
#
# Usage:
#   bash install.sh             # install into the current repo (.git/hooks)
#   bash install.sh --global    # install for every repo via core.hooksPath
#
# --global uses the directory core.hooksPath already points to, or sets it to
# ~/.config/git/hooks when it is unset.
#
# The hook itself is copied to <hooks dir>/strip-coauthor, and <hooks dir>/
# pre-push becomes a small dispatcher that runs, with the same arguments and
# stdin:
#   1. strip-coauthor
#   2. pre-push.chained    - whatever pre-push hook was there before installing
#                            (moved aside, never deleted)
#   3. the repo's own .git/hooks/pre-push, which git ignores once
#      core.hooksPath is set (skipped when that is the dispatcher itself)
# The first hook to fail stops the push.  Re-running the installer only
# refreshes strip-coauthor and the dispatcher.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HOOK_SRC="$SCRIPT_DIR/pre-push"
MARKER="strip-coauthor dispatcher"

GLOBAL=0
if [[ "${1:-}" == "--global" ]]; then
  GLOBAL=1
fi

if [[ "$GLOBAL" -eq 1 ]]; then
  EXISTING="$(git config --global --path core.hooksPath || true)"
  if [[ -n "$EXISTING" ]]; then
    TARGET_DIR="$EXISTING"
    echo "Using existing core.hooksPath: $TARGET_DIR"
  else
    TARGET_DIR="$HOME/.config/git/hooks"
    git config --global core.hooksPath "$TARGET_DIR"
    echo "Set core.hooksPath → $TARGET_DIR"
  fi
else
  GITDIR="$(git rev-parse --git-common-dir 2>/dev/null)" || {
    echo "Not inside a git repository." >&2; exit 1
  }
  TARGET_DIR="$GITDIR/hooks"
fi
mkdir -p "$TARGET_DIR"

DISPATCHER="$TARGET_DIR/pre-push"
CHAINED="$TARGET_DIR/pre-push.chained"

if [[ -e "$DISPATCHER" ]] && ! grep -q "$MARKER" "$DISPATCHER"; then
  if grep -q "strip-coauthor" "$DISPATCHER"; then
    # A pre-dispatcher copy of strip-coauthor itself: replace it.
    rm -f "$DISPATCHER"
  elif [[ -e "$CHAINED" ]]; then
    echo "Both $DISPATCHER and $CHAINED exist and neither is managed by" >&2
    echo "strip-coauthor.  Merge them by hand, then re-run the installer." >&2
    exit 1
  else
    mv "$DISPATCHER" "$CHAINED"
    echo "Kept existing hook: $CHAINED (runs after strip-coauthor)"
  fi
fi

cp "$HOOK_SRC" "$TARGET_DIR/strip-coauthor"
chmod +x "$TARGET_DIR/strip-coauthor"

cat > "$DISPATCHER" <<'SH'
#!/usr/bin/env bash
# strip-coauthor dispatcher (generated by install.sh; safe to re-generate).
# Runs strip-coauthor, then any chained pre-push hooks, with the same
# arguments and stdin.  The first failure stops the push.
set -euo pipefail

HOOK_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
INPUT="$(cat)"
[[ -n "$INPUT" ]] && INPUT+=$'\n'

run() {
  local hook="$1"; shift
  [[ -f "$hook" && -x "$hook" ]] || return 0
  printf '%s' "$INPUT" | "$hook" "$@"
}

run "$HOOK_DIR/strip-coauthor" "$@"
run "$HOOK_DIR/pre-push.chained" "$@"

REPO_HOOKS="$(git rev-parse --git-common-dir)/hooks"
if [[ -d "$REPO_HOOKS" && "$(cd "$REPO_HOOKS" && pwd -P)" != "$HOOK_DIR" ]]; then
  run "$REPO_HOOKS/pre-push" "$@"
fi
SH
chmod +x "$DISPATCHER"

echo "Installed: $DISPATCHER"
