#!/usr/bin/env bash
# Install strip-coauthor as git commit-msg and pre-push hooks.
#
# Usage:
#   bash install.sh             # install into the current repo (.git/hooks)
#   bash install.sh --global    # install for every repo via core.hooksPath
#
# --global uses the directory core.hooksPath already points to, or sets it to
# ~/.config/git/hooks when it is unset.
#
# Two hooks are installed:
#   commit-msg  strips the trailer when the commit is made, so SHAs never
#               change at push time.
#   pre-push    fallback for commits that skipped commit-msg; rewrites them
#               and stops the push.
#
# Each hook script is copied next to the dispatchers (pre-push as
# <hooks dir>/strip-coauthor, commit-msg as <hooks dir>/strip-coauthor-commit-
# msg), and <hooks dir>/<hook> becomes a small dispatcher that runs, with the
# same arguments (and stdin, for pre-push):
#   1. the strip-coauthor script
#   2. <hook>.chained      - whatever hook was there before installing
#                            (moved aside, never deleted)
#   3. the repo's own .git/hooks/<hook>, which git ignores once
#      core.hooksPath is set (skipped when that is the dispatcher itself).
#      By default only when there is no runnable chained hook: that hook
#      already decided whether the repo's hook runs before installing.
#      Override with `git config strip-coauthor.runRepoHook true|false`.
# The first hook to fail stops the commit or push.  Re-running the installer only
# refreshes strip-coauthor and the dispatcher.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MARKER="strip-coauthor dispatcher"

GLOBAL=0
if [[ "${1:-}" == "--global" ]]; then
  GLOBAL=1
fi

if [[ "$GLOBAL" -eq 1 ]]; then
  EXISTING="$(git config --global --path core.hooksPath || true)"
  if [[ -n "$EXISTING" ]]; then
    TARGET_DIR="$EXISTING"
    echo "Using existing core.hooksPath: $TARGET_DIR"
  else
    TARGET_DIR="$HOME/.config/git/hooks"
    git config --global core.hooksPath "$TARGET_DIR"
    echo "Set core.hooksPath → $TARGET_DIR"
  fi
else
  GITDIR="$(git rev-parse --git-common-dir 2>/dev/null)" || {
    echo "Not inside a git repository." >&2; exit 1
  }
  TARGET_DIR="$GITDIR/hooks"
fi
mkdir -p "$TARGET_DIR"

# install_hook <hook> <source script> <installed name> <read stdin 0|1> <header>...
# The headers are line 2 of earlier copies of the script itself: a hook
# starting with one of them was a bare copy (no dispatcher) and is replaced.
install_hook() {
  local hook="$1" src="$2" name="$3" read_stdin="$4"; shift 4
  local dispatcher="$TARGET_DIR/$hook" chained="$TARGET_DIR/$hook.chained"

  if [[ -e "$dispatcher" ]] && ! grep -qF "$MARKER" "$dispatcher"; then
    if sed -n 2p "$dispatcher" | grep -qxF "${@/#/-e}"; then
      rm -f "$dispatcher"
    elif [[ -e "$chained" ]]; then
      echo "Both $dispatcher and $chained exist and neither is managed by" >&2
      echo "strip-coauthor.  Merge them by hand, then re-run the installer." >&2
      exit 1
    else
      mv "$dispatcher" "$chained"
      echo "Kept existing hook: $chained (runs after strip-coauthor)"
    fi
  fi

  cp "$src" "$TARGET_DIR/$name"
  chmod +x "$TARGET_DIR/$name"

  sed -e "s/@HOOK@/$hook/g" -e "s/@SCRIPT@/$name/g" -e "s/@READ_STDIN@/$read_stdin/g" \
    > "$dispatcher" <<'SH'
#!/usr/bin/env bash
# strip-coauthor dispatcher (generated by install.sh; safe to re-generate).
# Runs @SCRIPT@, then any chained @HOOK@ hooks, with the same
# arguments (and stdin, when READ_STDIN=1).  The first failure stops git.
set -euo pipefail

HOOK_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
HOOK_NAME=@HOOK@
READ_STDIN=@READ_STDIN@
if [[ "$READ_STDIN" == 1 ]]; then
  INPUT="$(cat)"
  [[ -n "$INPUT" ]] && INPUT+=$'\n'
fi

runnable() { [[ -f "$1" && -x "$1" ]]; }

run() {
  local hook="$1"; shift
  runnable "$hook" || return 0
  if [[ "$READ_STDIN" == 1 ]]; then
    printf '%s' "$INPUT" | "$hook" "$@"
  else
    "$hook" "$@"
  fi
}

run "$HOOK_DIR/@SCRIPT@" "$@"
run "$HOOK_DIR/$HOOK_NAME.chained" "$@"

# Whether to also run the repo's own .git/hooks/<hook>, which git itself
# never runs once core.hooksPath points elsewhere.  Default: only when there
# is no chained hook.  A chained hook was in charge of that before strip-
# coauthor was installed (global hooks such as review-gate run it themselves),
# so leaving it to that hook keeps the exact pre-install behaviour and avoids
# running the repo hook twice.  Override per repo or globally with
#   git config strip-coauthor.runRepoHook true|false
RUN_REPO_HOOK="$(git config --type=bool strip-coauthor.runRepoHook || true)"
if [[ -z "$RUN_REPO_HOOK" ]]; then
  runnable "$HOOK_DIR/$HOOK_NAME.chained" && RUN_REPO_HOOK=false || RUN_REPO_HOOK=true
fi

REPO_HOOKS="$(git rev-parse --git-common-dir)/hooks"
if [[ "$RUN_REPO_HOOK" == true && -d "$REPO_HOOKS" &&
      "$(cd "$REPO_HOOKS" && pwd -P)" != "$HOOK_DIR" ]]; then
  run "$REPO_HOOKS/$HOOK_NAME" "$@"
fi
SH
  chmod +x "$dispatcher"
  echo "Installed: $dispatcher"
}

install_hook commit-msg "$SCRIPT_DIR/commit-msg" strip-coauthor-commit-msg 0 \
  "# strip-coauthor: git commit-msg hook that removes Co-Authored-By trailers from"
install_hook pre-push "$SCRIPT_DIR/pre-push" strip-coauthor 1 \
  "# strip-coauthor: git pre-push hook that removes Co-Authored-By trailers from" \
  "# Strip Co-Authored-By trailers from all commits that are about to be pushed."
